REF: refactoring Extensions.tsx file
asyncapi/asyncapi-react pull request #1063
Opened 2024-10-02 20:02 UTC by DhairyaMajmudar

**Description**

Changes proposed in this pull request:
-> Refactoring `Extensions.tsx` file by removing any keywords and typescript warnings disabling comments 

**Related issue(s)**
N/A

2024-10-07 18:17 UTC, AceTheCreator requested changes
Kindly look into why your build is failing :/

2024-10-08 16:13 UTC, DhairyaMajmudar commented
> Kindly look into why your build is failing :/

I've fixed them 👍🏻

2024-11-28 09:54 UTC, AceTheCreator requested changes
Left some reviews for you

2024-11-28 09:54 UTC, AceTheCreator commented on web-component/src/AsyncApiWebComponent.tsx
> +  schemaUrl?: string;
@DhairyaMajmudar the `schemaUrl` is not an optional value

2024-11-28 09:54 UTC, AceTheCreator commented on library/src/contexts/useSpec.ts
> +  React.createContext<AsyncAPIDocumentInterface>(null as never);
I think your changes here is unnecessarily strict and semantically incorrect in this scenario. I'd suggest we use the existing type :)

2024-11-28 09:54 UTC, AceTheCreator commented on library/src/components/Extensions.tsx
> -
I think this line should be removed

2025-01-12 07:47 UTC, closed without merging