added consistent styling for buttons and tags
asyncapi/asyncapi-react pull request #1099
Opened 2024-10-19 22:08 UTC by hargunkaur286

**Description**

This PR is related to the issue with inconsistent styling. According to the issue, "WCAG 2.0 guideline 3.2.4 Consistent Identification states "Components that have the same functionality within a set of Web pages are identified consistently". 

For example:
If we move to [async-react website](https://asyncapi.github.io/asyncapi-react/),
<img width="871" alt="Screenshot 2024-10-20 at 3 12 13 AM" src="https://github.com/user-attachments/assets/7ade1005-a7b5-495c-92d0-809319673453">
We will notice that there are multiple elements with a solid color background, but only some of them are a button.

Changes proposed in this pull request:

To resolve this, the ask in the issue was:
1. Buttons to be styled with rectangular outline.
2. Tags to be styled with solid background.

In this PR, changes have been made in 4 files:

1. **In "library/src/components/Schema.tsx" file:**
   Addresses the tags "Default values", "const", "Allowed values", "Example values".
   BEFORE:
   <img width="1203" alt="Screenshot 2024-10-20 at 3 30 26 AM" src="https://github.com/user-attachments/assets/6dec1312-1d16-4278-8428-d6cb510fa3ae">

   
   AFTER:
   <img width="1203" alt="Screenshot 2024-10-20 at 3 30 08 AM" src="https://github.com/user-attachments/assets/05236164-3725-4bb3-9513-505e20a43800">

2. **In "library/src/containers/Messages/Message.tsx" file**
    Addresses tags of "Correlation Id" and "Message Id"
   BEFORE:
   <img width="1203" alt="Screenshot 2024-10-20 at 3 32 54 AM" src="https://github.com/user-attachments/assets/0023fadb-1954-4304-9c24-ad389a0c506b">
   AFTER:
   
<img width="1203" alt="Screenshot 2024-10-20 at 3 33 28 AM" src="https://github.com/user-attachments/assets/e44e6277-6720-4a32-bb5c-e55a6bb63891">

3. **In "library/src/containers/Messages/MessageExample.tsx" file**
    Addresses the example labels
    BEFORE:
    <img width="1203" alt="Screenshot 2024-10-20 at 3 35 03 AM" src="https://github.com/user-attachments/assets/3c3fb780-523d-4713-b297-c97ba8cd901f">

    AFTER:
    
   <img width="1203" alt="Screenshot 2024-10-20 at 3 35 32 AM" src="https://github.com/user-attachments/assets/44640bcd-680f-4003-9199-a5554c10f7bc">

4. In "library/src/containers/Operations/Operation.tsx" file
    BEFORE:
    <img width="1203" alt="Screenshot 2024-10-20 at 3 36 44 AM" src="https://github.com/user-attachments/assets/e0162bf4-be3b-47af-8086-1e2a85a1ff44">

    AFTER:
    
    <img width="824" alt="Screenshot 2024-10-20 at 3 37 20 AM" src="https://github.com/user-attachments/assets/4568e771-099d-4468-88a3-cf0f3194e663">
   
   <img width="824" alt="Screenshot 2024-10-20 at 3 37 44 AM" src="https://github.com/user-attachments/assets/07771708-4cad-4828-884d-5556097a9bf8">

**Related issue(s)**

Resolves #960

2024-10-21 14:23 UTC, catosaurusrex2003 commented
> To resolve this, the ask in the issue
> 
> 1. Buttons to be styled with rectangular outline.
> 2. Tags to be styled with solid background.

I support this, also the changes are looking good.

However, I feel like there should be a `py-1` added to some of the tags which are being converted to solid.
![image](https://github.com/user-attachments/assets/7c1f92ef-7d94-410d-8182-81d626b1f755)
in the above 👆 example you can see that `lightMeasured Message ID` tags which you have made solid appear to be thinner than `format: date-time` 

This is my opinion, Please let me know what you think about this.

2024-10-23 07:32 UTC, AceTheCreator requested changes
@hargunkaur286 i don't think you should apply the changes to the messageExample.tsx file 🤔

2024-10-23 10:13 UTC, hargunkaur286 commented
> @hargunkaur286 i don't think you should apply the changes to the messageExample.tsx file 🤔

@AceTheCreator @catosaurusrex2003 Thank you for the feedback. I have removed the changes from messageExample.tsx file

2024-11-04 08:45 UTC, AceTheCreator approved these changes
LGTM! 

cc @catosaurusrex2003

2024-11-15 12:48 UTC, AceTheCreator commented
/rtm

2024-11-15 12:49 UTC, merged