feat: add web-component
asyncapi/asyncapi-react pull request #175
Opened 2020-11-03 13:56 UTC by magicmatatjahu

**Description**

Changes proposed in this pull request:

Improve web component to be production ready:
- Update code inside `web-component` folder,
- Update main Readme.md

**Related issue(s)**
See also https://github.com/asyncapi/asyncapi-react/pull/148

2020-11-03 19:34 UTC, gexclaude commented
Looks good to me - I'll be more than happy to check the README again as a user when switching from our custom build.

2020-11-06 11:57 UTC, derberg requested changes
LGTM
just 2 things:
- it should be published to `@asyncapi/web-component`
- can we rename `async-api-web-component.js` to `asyncapi-web-component.js` and any other `async-api` occurances too? 
- you need to have this https://github.com/asyncapi/html-template/blob/master/package.json#L28-L30 in package.json of webcomponent otherwise first publishing to npm will fail

2020-11-06 11:57 UTC, derberg commented on .github/workflows/release.yml
> +      - name: Install dependencies for library. web-component and playground
```suggestion
      - name: Install dependencies for library, web-component and playground
```

2020-11-09 10:58 UTC, magicmatatjahu commented
@derberg I propagated your suggestions to PR :)

2020-11-09 13:10 UTC, derberg approved these changes
LGTM
let's see if it works 😄

2020-11-12 13:40 UTC, merged