feat: config option to expand/collapse the examples payload
asyncapi/asyncapi-react pull request #621
Opened 2022-07-04 13:51 UTC by AceTheCreator

**Description**

Changes proposed in this pull request:
Ability to configure the default expand/collapse behavior for the "Examples" section.

**Related issue(s)**
#532

2022-07-05 10:30 UTC, AceTheCreator commented
@magicmatatjahu kindly review this PR. Let me know what you think :)

2022-07-05 10:33 UTC, magicmatatjahu requested changes
Awesome 🚀  but we need improve some things :)

2022-07-05 10:33 UTC, magicmatatjahu commented on library/src/config/config.ts
> +export interface ExpandedConfig {
```suggestion
export interface ExpandConfig {
```

2022-07-05 10:33 UTC, magicmatatjahu commented on library/src/containers/Messages/Message.tsx
> -
Leave that empty line :)

2022-07-05 10:33 UTC, magicmatatjahu commented on library/src/containers/Messages/MessageExample.tsx
> +    config && config.expand && config.expand.messageExamples,
```suggestion
    (config && config.expand && config.expand.messageExamples) || false,
```

2022-07-05 10:33 UTC, magicmatatjahu commented on playground/src/common/defaultConfig.ts
>    }
Here you should have valid JSON:

```suggestion
  "expand": {
    "messageExamples": false
  }
```

and probably by this config for playground didn't work for you.

2022-07-05 10:35 UTC, magicmatatjahu commented
@AceTheCreator Please also update documentation https://github.com/asyncapi/asyncapi-react/blob/next/docs/configuration/config-modification.md

2022-07-06 13:16 UTC, AceTheCreator commented
> @AceTheCreator Please also update documentation https://github.com/asyncapi/asyncapi-react/blob/next/docs/configuration/config-modification.md

@magicmatatjahu is the PR fine :)

2022-11-10 11:06 UTC, merged