feat: group Servers in sidebar navigation like Operation Objects
asyncapi/asyncapi-react pull request #682
Opened 2022-12-21 01:33 UTC by aeworxet

2022-12-22 10:29 UTC, magicmatatjahu requested changes
Good :) I added 3 suggestions.

2022-12-22 10:29 UTC, magicmatatjahu commented on library/src/helpers/specification.ts
> +  }
You try to make map of tags, but you should make rather array of tags, so please similar function to the `operationsTags`:

```suggestion
  static serversTags(spec: AsyncAPIDocument) {
    const tags = new Map<string, Tag>();
    Object.entries(spec.servers()).forEach(([_, server]) => {
      if (server.hasTags()) {
        server.tags().forEach(tag => tags.set(tag.name(), tag));
      }
    });
    return Array.from(tags.values());
  }
```

2023-01-16 08:41 UTC, derberg reviewed
@aeworxet even though it was not you that added duplicated code, sonar picked that up as you added some modifications to duplication-related-lines. This is why it is pinging you for changes.

IMHO it is ok if you report a separate issue for it and leave it out of scope for this PR

2023-01-31 13:57 UTC, magicmatatjahu approved these changes

2023-01-31 14:14 UTC, magicmatatjahu commented
@aeworxet Thanks for contribution!

2023-01-31 14:14 UTC, merged